### ISSUE TITLE
JavaScript gets purged from builder

### ISSUE THREAD

**Issue by alexhammerschmied** [Webmecanik/plugin-grapesjs-builder#14]
When I try to insert some custom JS into the page it gets deleted from the builder immediately. 
I saw that there is no regular component in GrapesJS for that. 
Is something planned for that? 
It would be an awesome feature for using the Mautic Focus Items on Landingpages as well.

**Comment by weismannweb** [comment]
I would suggest we use this:

https://github.com/artf/grapesjs-custom-code

**Comment by alexhammerschmied** [comment]
Yes.  I just changed in the builder.js the value for scripts from false to true and it works. But I think a button could be good to trigger that on each page individually. But maybe it can be turned on anyway... 
What do you think?
And yeah the custom code block would be amazing UX wise.

**Comment by alexhammerschmied** [comment]
I'll create a pr to enable scripts in the builder by default.
