### ISSUE TITLE
Instruction For mautic 3.x

### ISSUE THREAD

**Issue by bshowket** [Webmecanik/plugin-grapesjs-builder#19]
Hi Folks, Just wondering if the instruction "how to install in mautic 3.1" due to be change? I am following the guide as described https://github.com/Webmecanik/plugin-grapesjs-builder#installation-for-mautic-3x , as pull request 9050 already merged , i am guessing its only step 2 and 3 need to be done for 3.1 stable release , after doing step 2, mautic not detecting a new plugin . Am i missing anything? Thanks in advance

**Comment by jonathandhn** [comment]
I'm locked too this plugin. Not usable with Mautic 3 following the instructions... Dead links on the outdated doc and all. 
Download zip to /plugins, unzip, rename folder as GrapesJsBuilderBundle, chown code base as belonging to your server user, reload cache, reload plugins. DO NOTHING.
 ```
php bin/console mautic:plugins:reload
0 nouveaux plugins ont été installés et 0 mis à jour.
```
