### ISSUE TITLE
Upon cloning a MJML e-mail we loose the MJML data

### ISSUE THREAD

**Issue by rwrz** [Webmecanik/plugin-grapesjs-builder#23]
I have created a MJML template, then created an e-mail using it. So far, so good. E-mail sent!
Then, I want to clone this e-mail and just add or change other things, but when I clone it, it isn't a MJML e-mail anymore. 
It is using the HTML template builder. Or if we create an A/B testing, we loose the MJML builder as well.

Depending on the changes, this HTML builder will mess with the goodies of MJML.

I'm a developer as well and I'm happy to help to add this "cloning" feature to the MJML e-mails. I understood how the MJML works, but I'm not sure when to "clone" the MJML entities. Is there any EmailEvent that I can listen, then insert the MJML data?
Give me some path and I can send a PR with this feature.

**Comment by kuzmany** [comment]
From Mautic 3.1.2 you can use clone ID https://github.com/mautic/mautic/pull/9301  and EmailEvents::EMAIL_POST_SAVE If clone ID exists, copy the settings from grapejs entity to new one.

**Comment by rwrz** [comment]
Wow! Easier than I thought. Thank you for the tip.
I will try this today and send the PR if it works.

**Comment by adiux** [comment]
@rwrz Can this be closed?

**Comment by rwrz** [comment]
Sure. Sorry.
I will send a PR soon.

**Comment by adiux** [comment]
Thanks @rwrz ! Maybe you want to join us in the Builder initiative? We pick this up and make it part of the Mautic Community. The goal is to have an awesome Mautic builder from the community. Would be great if you join us here: https://mautic.slack.com/archives/C01EGF5U422

**Comment by kuzmany** [comment]
@adiux If it's not resolved . I can take it too. I've made it for another plugin already
