### ISSUE TITLE
email builder - ability to drop a dynamic slot into a text section

### ISSUE THREAD

**Issue by npracht** [Webmecanik/plugin-grapesjs-builder#4]
# Description
Today, when you drop a dynamic content slot, it goes on top or bottom of another slot (logic). The issue with that is that when you drop your DC slot, it does not have a style (it has a default style) and you need to set all the style (annoying).
- [ ] Add the ability to drop the DC slot into a text slot and it would replace it (keep all the same code and design, but transform it in DC).

**Comment by jos0405** [comment]
This seems to be fixed.
