### ISSUE TITLE
Turn off Mautic Global Shortcuts inside the pagebuilder and email builder

### ISSUE THREAD

**Issue by alexhammerschmied** [Webmecanik/plugin-grapesjs-builder#6]
The global shortcuts are still loaded inside the pagebuilder/emailbuilder.
This leads to big problems while writing/editing text. 
i.e. when you hit shift+d instead of writing an  uppercase "D" you end up in the dashboard. Which is confusing and sometimes very annoying...

**Comment by alexhammerschmied** [comment]
The builder closes also on several other phrases while typing text.

**Comment by rwrz** [comment]
Anyone knows how to do that? I will happy to send a PR to fix this one.

**Comment by weismannweb** [comment]
I fixed this.  I reset mousetrap which is what Mautic is using here: https://github.com/mautic/mautic/blob/8cb3c509a09224fe9c71abe84faebdb69c11c934/app/bundles/CoreBundle/Assets/js/1.core.js#L126

https://github.com/Webmecanik/plugin-grapesjs-builder/pull/25

Let me know if it looks good?
