### ISSUE TITLE
image upload in Email and Pagebuilder not working

### ISSUE THREAD

**Issue by alexhammerschmied** [Webmecanik/plugin-grapesjs-builder#7]
inside the pagebuilder when I click upload image i get the window to navigate to the image but when i click upload nothing happens.

**Comment by TornMarketing** [comment]
Having the same issue, the unload function is unresponsive

- I can upload images with the standard email builder, 
- If I move assets into the grapesjs media folder, they are visible in the grapes editor
- I can set the URL without issues

All file/folder permissions set at 775

**Comment by weismannweb** [comment]
Same here, this is a blocker for us to use this.  I had to switch back to the old editor.

**Comment by alexhammerschmied** [comment]
> Having the same issue, the unload function is unresponsive
> 
>     * I can upload images with the standard email builder,
> 
>     * If I move assets into the grapesjs media folder, they are visible in the grapes editor
> 
>     * I can set the URL without issues
> 
> 
> All file/folder permissions set at 775

yes that works for me as well. For the moment I have to deactivate the plugin in order to upload images. then activate it again and use the images inside the pagebuilder.

**Comment by TornMarketing** [comment]
A bit of a sloppy workaround but you can still access the file manager via the url /elfinder, then upload it to the grapesjs folder.
The only thing is that you need to have the assets loaded into the folder before you open the grapes builder, from what I have found you have to then save and exit the email to refresh the assets recognised to the folder. 

ie save, exit, upload images, then edit the email.

https://domain.com/elfinder 

Obviously not ideal but better than having to disable the plugin, upload then reactivate which would be a headache and a half.

Another note, grapesjs doesn't recognise folders within the grapgesjs folder, but will see the assets.
Thus, if you add a graphic with the path /grapesjs/test/image.jpg it will not show the folder structure in Grapes previewer, but it will show that image.jpg is available, when you insert the graphic the path then changes to /grapesjs/image.jpg thus breaking the URL

**Comment by alexhammerschmied** [comment]
> A bit of a sloppy workaround but you can still access the file manager via the url /elfinder, then upload it to the grapesjs folder.
> The only thing is that you need to have the assets loaded into the folder before you open the grapes builder, from what I have found you have to then save and exit the email to refresh the assets recognised to the folder.
> 
> ie save, exit, upload images, then edit the email.
> 
> https://domain.com/elfinder
> 
> Obviously not ideal but better than having to disable the plugin, upload then reactivate which would be a headache and a half.
> 
> Another note, grapesjs doesn't recognise folders within the grapgesjs folder, but will see the assets.
> Thus, if you add a graphic with the path /grapesjs/test/image.jpg it will not show the folder structure in Grapes previewer, but it will show that image.jpg is available, when you insert the graphic the path then changes to /grapesjs/image.jpg thus breaking the URL

Nice one! Thanks for the hint. This is somehow like the mediathek in wordpress then. That's ok for now. We're still in beta here...

**Comment by weismannweb** [comment]
Ii fixed this issue.  Now both the upload via url and the upload via drop zone and click on drop zone works.  

https://github.com/Webmecanik/plugin-grapesjs-builder/pull/26

We have another issue I found though which I will create an issue for.  It seems deleting images doesn't work.  The ajax returns success on the chrome console though so not sure whats happening.
